#!/usr/bin/env python
# -*- coding: utf-8 -*-

if __name__ == '__main__':
    from ozwmanager.ozwsh import Manager

    l = Manager()
    try:
        l.main()
    except Exception, e:
        l.debug('Error: %s' %e)
